"""
Anti-detection: each profile looks like an ordinary browser, consistent with the
device it claims to be, and has its own fingerprint that stays the same from one
session to the next.

- No automation marks: Chromium starts without "--enable-automation" (so
  navigator.webdriver is false and there is no "controlled by automated
  software" bar), and WebKit reports navigator.webdriver = false as well.
- Pop-up blocker on: Chromium keeps its own, and in WebKit a page can only open
  a window right after a click or a key press, as in Safari.
- Consistent identity: the desktop user-agent has the version of the real engine;
  the iPhone modes report the iPhone's platform, screen, pixel density, touch
  points and GPU, and in Chromium they hide what Safari does not have
  (userAgentData, window.chrome, deviceMemory, Notification).
- A fingerprint per profile: canvas and audio readouts carry a tiny noise derived
  from the profile's seed, invisible to the eye but enough to give every profile
  its own hashes, which do not change between sessions. Large canvases (photos
  being edited or uploaded) are left untouched.
- Natural languages: "es-ES" also lists "es", as browsers do.

Everything runs as an init script in every page and frame, before the page's own
scripts; the replaced functions look native (toString, name and length).
"""

from __future__ import annotations

import hashlib
import json
import re
from typing import Any

from profiles import Device, Profile, desktop_user_agent

# Chromium flags: Playwright's "--enable-automation" sets navigator.webdriver and shows
# the automation bar; "--disable-popup-blocking" would let any page open pop-ups.
CHROMIUM_IGNORED_ARGS = ["--enable-automation", "--disable-popup-blocking"]
CHROMIUM_ARGS = ["--disable-blink-features=AutomationControlled"]

NOISE_MAX_PIXELS = 600_000  # bigger canvases are photos, not fingerprints: never altered

# Screen height of each iPhone by the width of its viewport (Playwright only gives the viewport).
IPHONE_SCREENS = {320: 568, 390: 844, 393: 852, 402: 874, 414: 896, 420: 912, 428: 926, 430: 932, 440: 956}

# The user-agents the app generates for desktop mode; a hand-written one is left as is.
GENERATED_DESKTOP_UA = re.compile(
    r"^Mozilla/5\.0 \(Windows NT 10\.0; Win64; x64\) AppleWebKit/537\.36 \(KHTML, like Gecko\) "
    r"Chrome/\d+\.0\.0\.0 Safari/537\.36( Edg/\d+\.0\.0\.0)?$"
)


def user_agent_for(profile: Profile) -> str:
    """The user-agent to use: a desktop one generated by the app follows the engine's version
    (it was saved when the profile was created and the engine may have been updated since)."""
    if profile.mode == "desktop" and GENERATED_DESKTOP_UA.match(profile.user_agent):
        return desktop_user_agent()
    return profile.user_agent


def seed_of(profile: Profile) -> int:
    """The profile's fingerprint seed as a 32-bit number."""
    text = profile.seed or f"name:{profile.name}"
    return int.from_bytes(hashlib.sha256(text.encode("utf-8")).digest()[:4], "big")


def iphone_screen(device: Device) -> dict[str, int]:
    """Size of the iPhone's screen (the viewport leaves out Safari's bars)."""
    viewport: dict[str, int] = device.get("viewport", {"width": 390, "height": 664})
    width, viewport_height = viewport["width"], viewport["height"]
    if width == 375:  # iPhone SE / 8 (home button) or the 5.4" models
        height = 667 if viewport_height < 600 else 812
    else:
        height = IPHONE_SCREENS.get(width) or round(viewport_height * 1.29)
    return {"width": width, "height": height}


def languages(locale: str, engine: str, mode: str) -> list[str]:
    """navigator.languages: Chrome lists the language without region too; Safari only one."""
    base = locale.split("-")[0]
    if (mode == "iphone" and engine == "webkit") or base == locale:
        return [locale]
    return [locale, base]


def accept_language(languages_: list[str]) -> str:
    """The Accept-Language header for those languages, e.g. "es-ES,es;q=0.9"."""
    parts = [languages_[0], *(f"{language};q={0.9 - 0.1 * index:.1f}" for index, language in enumerate(languages_[1:]))]
    if len(languages_) == 1 and "-" in languages_[0]:
        parts.append(f"{languages_[0].split('-')[0]};q=0.9")
    return ",".join(parts)


def config_for(profile: Profile, device: Device | None) -> dict[str, Any]:
    iphone = profile.mode == "iphone"
    chromium = profile.engine == "chromium" or profile.mode == "desktop"
    config: dict[str, Any] = {
        "seed": seed_of(profile),
        "noiseMaxPixels": NOISE_MAX_PIXELS,
        "languages": languages(profile.locale, profile.engine, profile.mode),
        "webdriver": not chromium,  # Chromium already reports false thanks to its flags
        "blockPopups": not chromium,  # Chromium blocks them itself; Playwright's WebKit does not
        "iphone": None,
    }
    if iphone and device is not None:
        screen = iphone_screen(device)
        config["iphone"] = {
            "screen": [screen["width"], screen["height"]],
            "pixelRatio": device.get("device_scale_factor", 3),
            "chromium": chromium,
        }
    return config


def init_script(profile: Profile, device: Device | None) -> str:
    return SCRIPT.replace("__CONFIG__", json.dumps(config_for(profile, device)))


SCRIPT = r"""
(() => {
  const config = __CONFIG__;

  // --- replaced functions look native -------------------------------------
  const nativeNames = new WeakMap();
  const originalToString = Function.prototype.toString;
  const toString = { toString() {
    return nativeNames.has(this)
      ? `function ${nativeNames.get(this)}() { [native code] }`
      : originalToString.call(this);
  } }.toString;
  nativeNames.set(toString, 'toString');
  Object.defineProperty(Function.prototype, 'toString', {
    value: toString, writable: true, configurable: true, enumerable: false,
  });

  const setGetter = (target, prop, value) => {
    if (!target) return;
    const previous = Object.getOwnPropertyDescriptor(target, prop);
    const get = Object.getOwnPropertyDescriptor({ get [prop]() { return value(); } }, prop).get;
    nativeNames.set(get, 'get ' + prop);
    Object.defineProperty(target, prop, {
      get,
      set: previous ? previous.set : undefined,
      configurable: true,
      enumerable: previous ? previous.enumerable : true,
    });
  };
  const remove = (target, prop) => {
    try { if (target) delete target[prop]; } catch (error) { /* not configurable */ }
  };
  const wrap = (target, prop, implementation) => {
    if (!target) return;
    const original = target[prop];
    if (typeof original !== 'function') return;
    const replacement = { [prop](...args) { return implementation.call(this, original, args); } }[prop];
    Object.defineProperty(replacement, 'length', { value: original.length });
    nativeNames.set(replacement, prop);
    Object.defineProperty(target, prop, { ...Object.getOwnPropertyDescriptor(target, prop), value: replacement });
  };

  // --- identity ------------------------------------------------------------
  if (config.webdriver) setGetter(Navigator.prototype, 'webdriver', () => false);
  // Pop-up blocker, as in Safari: a page opens windows only right after a click or a key.
  if (config.blockPopups && navigator.userActivation) {
    wrap(window, 'open', function (original, args) {
      return navigator.userActivation.isActive ? original.apply(this, args) : null;
    });
  }
  const languages = Object.freeze([...config.languages]);
  setGetter(Navigator.prototype, 'languages', () => languages);
  setGetter(Navigator.prototype, 'language', () => languages[0]);

  const iphone = config.iphone;
  if (iphone) {
    setGetter(Navigator.prototype, 'platform', () => 'iPhone');
    setGetter(Navigator.prototype, 'maxTouchPoints', () => 5);
    const [width, height] = iphone.screen;
    const sizes = [['width', width], ['height', height], ['availWidth', width], ['availHeight', height]];
    for (const [prop, value] of sizes) {
      setGetter(Screen.prototype, prop, () => value);
    }
    const ratioTarget = Object.getOwnPropertyDescriptor(window, 'devicePixelRatio') ? window : Window.prototype;
    setGetter(ratioTarget, 'devicePixelRatio', () => iphone.pixelRatio);
    if (iphone.chromium) {
      setGetter(Navigator.prototype, 'vendor', () => 'Apple Computer, Inc.');
      remove(Navigator.prototype, 'userAgentData');
      remove(Navigator.prototype, 'deviceMemory');
      remove(window, 'chrome');
      remove(window, 'Notification');
      const gpu = function (original, args) {
        if (args[0] === 37445) return 'Apple Inc.';  // UNMASKED_VENDOR_WEBGL
        if (args[0] === 37446) return 'Apple GPU';  // UNMASKED_RENDERER_WEBGL
        return original.apply(this, args);
      };
      wrap(window.WebGLRenderingContext && WebGLRenderingContext.prototype, 'getParameter', gpu);
      wrap(window.WebGL2RenderingContext && WebGL2RenderingContext.prototype, 'getParameter', gpu);
    }
  }

  // --- a fingerprint of its own: tiny noise, the same in every session ----------
  const seed = config.seed >>> 0;
  const hash = (n) => {
    let x = (seed ^ Math.imul(n + 1, 0x9E3779B1)) >>> 0;
    x ^= x << 13; x >>>= 0; x ^= x >>> 17; x ^= x << 5;
    return x >>> 0;
  };
  // Flips the lowest bit of one channel in about 1 of every 64 opaque pixels, chosen by position.
  const noisify = (data, canvasWidth, left, top, width) => {
    for (let i = 0; i < data.length; i += 4) {
      if (data[i + 3] !== 255) continue;
      const pixel = i >> 2;
      const h = hash((top + Math.floor(pixel / width)) * canvasWidth + left + (pixel % width));
      if ((h & 63) === 0) data[i + ((h >>> 6) % 3)] ^= 1;
    }
  };
  const small = (canvas) => canvas && canvas.width > 0 && canvas.height > 0
    && canvas.width * canvas.height <= config.noiseMaxPixels;
  const context2d = window.CanvasRenderingContext2D && CanvasRenderingContext2D.prototype;
  const getImageData = context2d && context2d.getImageData;
  const putImageData = context2d && context2d.putImageData;
  if (context2d) {
    wrap(context2d, 'getImageData', function (original, args) {
      const image = original.apply(this, args);
      if (small(this.canvas)) noisify(image.data, this.canvas.width, args[0] | 0, args[1] | 0, image.width);
      return image;
    });
    const noisyCopy = (canvas) => {
      if (!small(canvas)) return null;
      try {
        const copy = document.createElement('canvas');
        copy.width = canvas.width; copy.height = canvas.height;
        const context = copy.getContext('2d');
        context.drawImage(canvas, 0, 0);
        const image = getImageData.call(context, 0, 0, copy.width, copy.height);
        noisify(image.data, copy.width, 0, 0, copy.width);
        putImageData.call(context, image, 0, 0);
        return copy;
      } catch (error) {
        return null;  // e.g. a canvas with images from another site: the original throws as it should
      }
    };
    for (const prop of ['toDataURL', 'toBlob']) {
      wrap(HTMLCanvasElement.prototype, prop, function (original, args) {
        return original.apply(noisyCopy(this) || this, args);
      });
    }
  }
  if (window.AudioBuffer) {
    const touched = new WeakSet();
    wrap(AudioBuffer.prototype, 'getChannelData', function (original, args) {
      const data = original.apply(this, args);
      if (!touched.has(data)) {
        touched.add(data);
        for (let i = 0; i < data.length; i += 97) data[i] += ((hash(i) & 255) - 127.5) * 1e-9;
      }
      return data;
    });
  }
})();
"""
